

[colors]
[colors.primary]
background = "#101010"
foreground = "#d4d4d4"
dim_foreground = "#A0A0A0"

[colors.cursor]
text = "CellBackground"
cursor = "#ffffff"

[colors.selection]
text = "CellForeground"
background = "#232323"

[colors.normal]
black = "#1C1C1C"
red = "#FF8080"
green = "#99FFE4"
yellow = "#FFC799"
blue = "#A0A0A0"
magenta = "#FFCFA8"
cyan = "#99FFE4"
white = "#CFCFCF"

[colors.bright]
black = "#505050"
red = "#FF9A9A"
green = "#B8FFF0"
yellow = "#FFCFA8"
blue = "#D0D0D0"
magenta = "#FFB0B0"
cyan = "#B8FFF0"
white = "#FFFFFF"
